const express = require('express')
const app = express()
const user = require('./user')
const about = require('./About')
const home = require('./home')
const contact = require('./contact')
const feedback = require('./feedback')
app.get('/',(request,response)=>
    response.send("This is main page"))
app.use('/user',user)
app.use('/about',about)
app.use('/home',home)
app.use('/contact',contact)
app.use('/feedback',feedback)
app.listen(1008)